### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by howtowhy** [simonkamronn/kvae#1]
Hello, thanks for the nice code.
I have a problem to construct config.json file in log folder.
Please help me.
the error was like this.
I am using Pycharm IDE and run the run_kvae.py

----------------------------------------------------
Traceback (most recent call last):
  File "C:/dev/kvae-master/kvae-master/examples/run_kvae.py", line 58, in <module>
    lb = run()
  File "C:/dev/kvae-master/kvae-master/examples/run_kvae.py", line 36, in run
    json.dump(config.__flags, f)
  File "C:\Users\Stella\Anaconda3\lib\json\__init__.py", line 178, in dump
    for chunk in iterable:
  File "C:\Users\Stella\Anaconda3\lib\json\encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\Stella\Anaconda3\lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Users\Stella\Anaconda3\lib\json\encoder.py", line 436, in _iterencode
    o = _default(o)
  File "C:\Users\Stella\Anaconda3\lib\json\encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <absl.flags._flag.Flag object at 0x0000000021AD37B8> is not JSON serializable

**Comment by howtowhy** [comment]
I fix this error with "list".
It is more robust to read json format. will pull request it :)

**Comment by airwayneeee** [comment]
Hi, @howtowhy do you mind sharing how you fix the issue? I had the same problem

**Comment by simonkamronn** [comment]
Fix is merged in https://github.com/simonkamronn/kvae/pull/2
